#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")

#@ data.values.registry.server or assert.fail("missing registry.server")
#@ data.values.registry.repository or assert.fail("missing registry.repository")
---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: tekton-supply-chain
spec:
  selectorMatchExpressions:
    - key: 'apps.tanzu.vmware.com/workload-type'
      operator: In
      values: 
      - tekton

  params:
    - name: maven_repository_url
      value: #@ data.values.maven.repository.url
    #@ if/end data.values.maven.repository.secret_name:
    - name: maven_repository_secret_name
      value: #@ data.values.maven.repository.secret_name

    - name: gitops_branch
      default: #@ data.values.gitops.branch
    - name: gitops_user_name
      default: #@ data.values.gitops.username
    - name: gitops_user_email
      default: #@ data.values.gitops.email
    - name: gitops_commit_message
      default: #@ data.values.gitops.commit_message
    - name: gitops_ssh_secret
      default: #@ data.values.gitops.ssh_secret
    #@ if/end data.values.gitops.repository_prefix:
    - name: gitops_repository_prefix
      default: #@ data.values.gitops.repository_prefix
    #@ if/end data.values.gitops.server_address:
    - name: gitops_server_address
      default: #@ data.values.gitops.server_address
    #@ if/end data.values.gitops.repository_owner:
    - name: gitops_repository_owner
      default: #@ data.values.gitops.repository_owner
    #@ if/end data.values.gitops.repository_name:
    - name: gitops_repository_name
      default: #@ data.values.gitops.repository_name
    #@ if/end data.values.gitops.pull_request.server_kind:
    - name: gitops_server_kind
      default: #@ data.values.gitops.pull_request.server_kind
    #@ if/end "commit_branch" in data.values.gitops.pull_request:
    - name: gitops_commit_branch
      default: #@ data.values.gitops.pull_request.commit_branch
    #@ if/end data.values.gitops.pull_request.pull_request_title:
    - name: gitops_pull_request_title
      default: #@ data.values.gitops.pull_request.pull_request_title
    #@ if/end data.values.gitops.pull_request.pull_request_body:
    - name: gitops_pull_request_body
      default: #@ data.values.gitops.pull_request.pull_request_body

  resources:
  - name: source-provider
    templateRef:
      kind: ClusterSourceTemplate
      name: source-template
    params:
      - name: serviceAccount
        default: #@ data.values.service_account
      - name: gitImplementation
        value: #@ data.values.git_implementation

  - name: runnable-pipeline
    templateRef:
      kind: ClusterSourceTemplate
      name: tekton-runnable-pipeline
    sources:
    - resource: source-provider
      name: source
  
  - name: norunnable-pipeline
    templateRef:
      kind: ClusterSourceTemplate
      name: tekton-norunnable-pipeline
    sources:
    - resource: runnable-pipeline
      name: source
  
  - name: norunnable-pipeline2
    templateRef:
      kind: ClusterSourceTemplate
      name: tekton-norunnable-pipeline
    sources:
    - resource: norunnable-pipeline
      name: source

  - name: runnable-task
    templateRef:
      kind: ClusterSourceTemplate
      name: tekton-runnable-task
    sources:
    - resource: norunnable-pipeline2
      name: source
  
  - name: norunnable-task
    templateRef:
      kind: ClusterSourceTemplate
      name: tekton-norunnable-task
    sources:
    - resource: runnable-task
      name: source

  - name: norunnable-task2
    templateRef:
      kind: ClusterSourceTemplate
      name: tekton-norunnable-task
    sources:
    - resource: norunnable-task
      name: source

