apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tekton-task
spec:
  params:
  - name: source-url
    type: string
  - name: source-revision
    type: string
  - default: ""
    name: sub-path
    type: string
  - default: ""
    name: fail-at
    type: string
  steps:
  - image: maven:3.8.6
    name: test
    resources: {}
    script: |
      #!/bin/bash
          
      echo "Displaying all labels"
      if [[ -e /etc/podinfo/labels ]]; then
        cat /etc/podinfo/labels
      fi

      echo ""

      LABEL=carto.run/resource-name
      RESOURCE_NAME=$(cat /etc/podinfo/labels | grep $LABEL | sed 's|carto.run/resource-name=||' | sed 's|"||g')
      
      echo "RESOURCE_NAME=$RESOURCE_NAME"
      echo "SUBPATH=$(params.sub-path)"

      if [[ "$(params.fail-at)" == "$RESOURCE_NAME" ]]; then
        echo "Deliberate Failure"
        exit 1
      else 
        echo "Task allowed to pass"
      fi
    volumeMounts:
    - name: podinfo
      mountPath: /etc/podinfo
