---
apiVersion: carto.run/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: tekton-norunnable-pipeline
spec:
  urlPath: .status.outputs.url
  revisionPath: .status.outputs.revision

  healthRule:
    singleConditionType: Succeeded

  template:
    apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: tekton-norunnable-pipeline-run-
      labels:
        app.kubernetes.io/part-of: $(workload.metadata.name)$
    spec:
      pipelineRef:
        name: tekton-pipeline
      params:
        - name: source-url
          value: $(source.url)$
        - name: source-revision
          value: $(source.revision)$
        - name: sub-path
          value: $(workload.spec.source.subPath)$
      podTemplate:
        volumes:
        - name: podinfo
          downwardAPI:
            items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
            - path: "annotations"
              fieldRef:
                fieldPath: metadata.annotations    

  urlPath: .status.pipelineSpec.tasks[0].params[0].value
  revisionPath: .status.pipelineSpec.tasks[0].params[1].value
  lifecycle: tekton
