---
apiVersion: carto.run/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: tekton-norunnable-task
spec:
  urlPath: .status.outputs.url
  revisionPath: .status.outputs.revision

  healthRule:
    singleConditionType: Succeeded

  template:
    apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      generateName: tekton-norunnable-task-run-
      labels:
        app.kubernetes.io/part-of: $(workload.metadata.name)$
    spec:
      taskRef:
        name: tekton-task
      params:
        - name: source-url
          value: $(source.url)$
        - name: source-revision
          value: $(source.revision)$
        - name: sub-path
          value: $(workload.spec.source.subPath)$
        - name: fail-at
          value: $(workload.params.fail-at)$
      podTemplate:
        volumes:
        - name: podinfo
          downwardAPI:
            items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
            - path: "annotations"
              fieldRef:
                fieldPath: metadata.annotations    

  urlPath: .spec.params[0].value
  revisionPath: .spec.params[1].value
  lifecycle: tekton
